Webcore/Areas/Admin/Controllers/SuccessStoryController.cs
// <copyright file="SuccessStoryController.cs" company="Dasigno">
//     Copyright (c) 2013 All Rights Reserved
// </copyright>
// <author>Diego Toro</author>
namespace Webcore.Areas.Admin.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    using Business;
    using Business.Services;
    using Domain.Concrete;
    using Domain.Entities.FrontEnd;
    using Webcore.Areas.Admin.Models;
    using Core.Facades;
    using Domain.Entities;

    /// <summary>
    /// Controller for SuccessStoryEntry module
    /// </summary>
    [ModulAuthorize]
    public class SuccessStoryController : AdminController
    {
        /// <summary>
        /// gets the home of SuccessStoryEntry module
        /// </summary>
        /// <param name="mod">identifier of module</param>
        /// <param name="sectionId">identifier of section</param>
        /// <param name="idpostulate">Id de la postulacion</param>
        /// <returns>returns the result to action</returns>
        public ActionResult Index(int mod, int? sectionId, int? idpostulate)
        {
            ContentManagement objcontentman = new ContentManagement(this.SessionCustom, HttpContext);
            SectionRepository objsection = new SectionRepository(this.SessionCustom);
            TemplateRepository objtemplate = new TemplateRepository(this.SessionCustom);
            TagFacade tagFacade = new TagFacade();
            objtemplate.Entity.Type = 2;

            if (idpostulate != null)
            {
                Core.Facades.SuccessStoryPostulateFacade dbpostulate = new SuccessStoryPostulateFacade();

                Domain.Entities.Generic.SuccessStoryPostulate postulate = dbpostulate.GetById(idpostulate.Value, this.CurrentLanguage.LanguageId.Value);
                Domain.Entities.SuccessStory successtory = new Domain.Entities.SuccessStory();
                Domain.Entities.Content content = new Domain.Entities.Content();

                content.ModulId = mod;
                content.SectionId = sectionId;

                if (postulate.LanguageId == (int)Domain.Entities.Enums.LanguageEnum.English)
                {
                    content.NameIngles = postulate.Name;
                    successtory.DescriptionIngles = postulate.Description;
                    successtory.ProblemsSolvedIngles = postulate.ConcreteProblems;
                    successtory.SocialImpactIngles = postulate.InnovativeUrbanSolution;
                }
                else
                {
                    content.Name = postulate.Name;
                    successtory.Description = postulate.Description;
                    successtory.ProblemsSolved = postulate.ConcreteProblems;
                    successtory.SocialImpact = postulate.InnovativeUrbanSolution;
                }

                content.Category = postulate.CategoryName;
                content.UserId = postulate.UserId;
                content.LanguageId = postulate.LanguageId;
                successtory.InstitutionImplements = postulate.ResponsibleOrganization;
                successtory.InstitutionSource = postulate.ResponsibleNames;
                successtory.Category = postulate.CategoryName;
                successtory.Url = postulate.Documents;
                successtory.CityID = postulate.CityId;

                IList<Tag> listaTags = tagFacade.GetBySuccessStoryPostulate(idpostulate.Value);
                string tagsNews = string.Empty;
                string existingTags = string.Empty;

                foreach (Tag temp in listaTags)
                {
                    if (temp.TagId != null)
                    {
                        existingTags += temp.TagId + "|";
                    }
                    else
                    {
                        tagsNews += temp.Name + "|";
                    }
                }

                if (tagsNews.EndsWith("|"))
                {
                    tagsNews = tagsNews.Substring(0, tagsNews.Length - 1);
                }

                if (existingTags.EndsWith("|"))
                {
                    existingTags = existingTags.Substring(0, existingTags.Length - 1);
                }

                this.ViewBag.SelectedTags = existingTags;
                this.ViewBag.NewsTags = tagsNews;

                return this.View(new SuccessStoryModel()
                {
                    PostulateId = idpostulate,
                    SuccessStory = successtory,
                    IContent = content,
                    UserPrincipal = this.CustomUser,
                    Module = this.Module,
                    ColModul = CustomMemberShipProvider.GetModuls(this.CustomUser.UserId, this.SessionCustom, HttpContext),
                    Templates = objtemplate.GetAll().Select(t => t.TemplateId),
                    DeepFollower = sectionId != null ? Business.Utils.GetDeepFollower(objsection.GetAll(), sectionId.Value) : null,
                    CurrentLanguage = this.CurrentLanguage,
                    Tags = tagFacade.GetAll().Select(t => new SelectListItem { Text = t.Name, Value = t.TagId.ToString() })
                });
            }

            return this.View(new SuccessStoryModel()
            {
                UserPrincipal = this.CustomUser,
                Module = this.Module,
                ColModul = CustomMemberShipProvider.GetModuls(this.CustomUser.UserId, this.SessionCustom, HttpContext),
                Templates = objtemplate.GetAll().Select(t => t.TemplateId),
                DeepFollower = sectionId != null ? Business.Utils.GetDeepFollower(objsection.GetAll(), sectionId.Value) : null,
                IContent = new Domain.Entities.Content()
                {
                    ModulId = mod,
                    SectionId = sectionId
                },
                CurrentLanguage = this.CurrentLanguage,
                Tags = tagFacade.GetAll().Select(t => new SelectListItem { Text = t.Name, Value = t.TagId.ToString() })
            });
        }

        /// <summary>
        /// obtains the challenge detail
        /// </summary>
        /// <param name="mod">identifier of module</param>
        /// <param name="id">identifier of section</param>
        /// <param name="sectionId">seccion del molulo</param>
        /// <returns>returns the result to action</returns>
        public ActionResult Detail(int mod, int id, int? sectionId)
        {
            ContentManagement objcontentman = new ContentManagement(SessionCustom, HttpContext);
            ContentRepository objcontent = new ContentRepository(SessionCustom);
            SuccessStoryRepository objSuccessStory = new SuccessStoryRepository(SessionCustom);
            FileattachRepository objfiles = new FileattachRepository(SessionCustom);
            TagRepository objtag = new TagRepository(SessionCustom);
            SectionRepository objsection = new SectionRepository(SessionCustom);
            TemplateRepository objtemplate = new TemplateRepository(SessionCustom);
            CommentRepository objcomment = new CommentRepository(SessionCustom);
            TagFacade tagFacade = new TagFacade();

            objtemplate.Entity.Type = 0;

            objSuccessStory.Entity.ContentId =
                objfiles.Entity.ContentId =
                objcomment.Entity.ContentId = 
                objcontent.Entity.ContentId = id;

            objSuccessStory.LoadByKey();
            objcontent.LoadByKey();

            int totalComments = 0;
            List<CommentsPaging> comments = objcomment.CommentsPagingContent(0, 50, out totalComments, id);
            ViewBag.TotalComments = totalComments;

            IEnumerable<Tag> SelectedTags = objtag.GetTagbycontent(id);
            this.ViewBag.SelectedTags = string.Join("|", SelectedTags.Select(t => t.TagId));
            this.ViewBag.NewsTags = string.Empty;

            return this.View(
                "Index",
                new SuccessStoryModel()
                {
                    UserPrincipal = this.CustomUser,
                    ColModul = CustomMemberShipProvider.GetModuls(this.CustomUser.UserId, this.SessionCustom, HttpContext),
                    Module = this.Module,
                    ListFiles = objfiles.GetAllReadOnly(),
                    SuccessStory = objSuccessStory.Entity,
                    IContent = objcontent.Entity,
                    Templates = objtemplate.GetAll().Select(t => t.TemplateId),
                    ListContent = objcontent.GetContentRelation(CurrentLanguage.LanguageId.Value),
                    ListTags = SelectedTags,
                    DeepFollower = Business.Utils.GetDeepFollower(objsection.GetAll(), objcontent.Entity.SectionId.Value),
                    CurrentLanguage = this.CurrentLanguage,
                    ListComments = comments,
                    Tags = tagFacade.GetAll().Select(t => new SelectListItem { Text = t.Name, Value = t.TagId.ToString() })
                });
        }

        /// <summary>
        /// inserts or updates a item SuccessStory entry
        /// </summary>
        /// <param name="model">identifier of module</param>
        /// <param name="contentImage">represents a upload content image</param>
        /// <param name="contentCoverImage">represents a upload content cover image</param>
        /// <param name="videoyoutube">represents a list of videos</param>
        /// <returns>returns the result to action</returns>
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(SuccessStoryModel model, HttpPostedFileBase contentImage, HttpPostedFileBase contentCoverImage, List<string> videoyoutube, string existingTags, string newTags)
        {
            SuccessStoryRepository objSuccessStory = new SuccessStoryRepository(this.SessionCustom);
            ContentManagement objcontent = new ContentManagement(this.SessionCustom, HttpContext);

            try
            {

Webcore/Controllers/SuccessStoryController.cs
// <copyright file="SuccessStoryController.cs" company="Intergrupo">
//     Copyright (c) 2013 All Rights Reserved
// </copyright>
// <author>Ferney Osorio</author>
namespace Webcore.Controllers
{
   using System;
   using System.Configuration;
   using System.Web.Mvc;
   using Business.Services;
   using Core.Facades;
   using Domain.Concrete;
   using Domain.Entities;
   using Domain.Entities.FrontEnd;
   using Webcore.Models;

    /// <summary>
    /// Controler from Success Case
    /// </summary>
    public class SuccessStoryController : FrontEndController
    {
        /// <summary>
        /// Presenta la el detalle del casos de exito.
        /// </summary>
        /// <param name="id">Id del caso de exito</param>
        /// <returns>Retorna la vista</returns>
        public ActionResult Story(int id = 0)
        {
            int? currentUserId = null;
            this.UpdateLanguage();
            FrontEndManagement objmanagement = new FrontEndManagement(this.SessionCustom, HttpContext, FrontEndManagement.Type.Content, this.CurrentLanguage);
            UserRepository user = new UserRepository(this.SessionCustom);
            SuccessStoryFacade successCase = new SuccessStoryFacade();
            SuccessStoryList collSuccessCase = successCase.GetById(id, this.CurrentLanguage.LanguageId);
            IdeaRepository idea = new IdeaRepository(this.SessionCustom);
            FileattachRepository file = new FileattachRepository(this.SessionCustom);
            FESuccessStory story = new FESuccessStory();

            if (User.Identity.IsAuthenticated)
            {
                currentUserId = ((CustomPrincipal)User).UserId;
                objmanagement.BindInfo(id, currentUserId);
                ViewBag.CurrentUserId = currentUserId;
            }
            else
            {
                objmanagement.BindInfo(id, null);
            }

            story.Story = collSuccessCase;

            if (story.Story.UserId > 0)
            {
                user.Entity.UserId = story.Story.UserId;
                user.LoadByKey();
            }

            file.Entity.ContentId = id;
            string[] opciones = new string[] { "\r\n" };
            string[] urls = collSuccessCase.Url.Split(opciones, StringSplitOptions.None);

            this.ViewBag.Urls = urls;

            story.CollFiles = file.GetAll();
            story.ObjUser = user.Entity;
            story.MetaTags = objmanagement.Metatags;
            story.UserPrincipal = this.CustomUser;
            story.CurrentLanguage = this.CurrentLanguage;
            story.IdeasCountAll = idea.IdeasCountAll();
            story.Section = objmanagement.Section;
            story.PageTitle = string.Format("{0} | {1}", ConfigurationManager.AppSettings["TitleHome"], story.Story.Name);

            return View(story);
        }

        /// <summary>
        /// Update Language
        /// </summary>
        private void UpdateLanguage()
        {
            if (HttpContext.Session["lang"] != null)
            {
                this.CurrentLanguage = (Language)HttpContext.Session["lang"];
            }
            else
            {
                LanguageRepository languagerepo = new LanguageRepository(this.SessionCustom);
                languagerepo.GetByUser(this.CustomUser.UserId);
                this.CurrentLanguage = languagerepo.Entity;
                if (this.CurrentLanguage.Name != null)
                {
                    HttpContext.Session.Add("lang", this.CurrentLanguage);
                }
                else
                {
                    languagerepo.GetLanguageDefault();
                    HttpContext.Session.Add("lang", this.CurrentLanguage);
                }

            }
        }
    }
}

Webcore/Areas/Admin/Views/SuccessStory/Index.cshtml
@model Webcore.Areas.Admin.Models.SuccessStoryModel
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@section headers {
    <script src="@Url.Content("~/Resources/Scripts/jquery.fcbkcomplete.min.js")" type="text/javascript"></script>
    @Scripts.Render("~/bundles/jquerycl")
    <script type="text/javascript" language="javascript">
        var tempfiles = new Array();
        var editor;
        var editor2;
        var ProblemsSolvedEditor;
        var ProblemsSolvedEditor2;
        var SocialImpactEditor;
        var SocialImpactEditor2;

        $(document).ready(function () {
            $.cleditor.defaultOptions.height = 500;
            $.cleditor.defaultOptions.width = 720;
            $.cleditor.defaultOptions.docCSSFile = '@Url.Content("~/Resources/Css/frontend.styles.css")'
            $.cleditor.buttons.image.uploadUrl = '@(Url.Action("UploadImage", "Content", new { Area = "Admin" }) + (Model.IContent != null && Model.IContent.ContentId != null ? "?id=" + Model.IContent.ContentId : ""))';
            hideTemplates('blog');
            $('#Form1').submit(function (event) {
                var valid = true;

                $('#contentNeeded').remove();
                if ($('#BlogEntry_Description').val() == "") {
                    valid = false;
                }

                if (!valid) {
                    if ($('.validation-summary-valid li').length <= 1 && $('.validation-summary-valid li').html() == '') {
                        $('.validation-summary-valid').removeClass('validation-summary-valid').addClass('validation-summary-errors');
                    }
                    $('.validation-summary-errors ul').append('<li id="contentNeeded">Debes ingresar un contenido</li>');
                    event.preventDefault();
                }
            });
            (function ($) {
                $.cleditor.defaultOptions.docType = "<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>";
                $.cleditor.defaultOptions.updateTextArea = function (html) { //if (document.forms[0].debugArea) document.forms[0].debugArea.value = html;
                    // Normalize to xhtml/html5 common standards and only keep allowed tags.
                    var ary = html.split("<");
                    var end = -1;
                    for (var i = 0; i < ary.length; i++) {
                        if (ary[i].lastIndexOf("!--[if ", 7) === 0) { // handle Microsoft <!--[if ... <![endif]-->
                            ary[i] = "";
                            var found = false;
                            for (i++; i < ary.length; i++) {
                                if (ary[i].lastIndexOf("![endif]-->", 11) === 0) { found = true; }
                                ary[i] = "";
                                if (found) break;
                            }
                            if (i >= ary.length) break;
                        }
                        end = ary[i].indexOf(">");
                        if (end == -1) continue;
                        ary[i] = ary[i].substring(0, end).toLowerCase() + ary[i].substring(end);
                        var search = ["strong>", "em>", "strike>", "u>", "br>"];
                        var replace = ["b>", "i>", "del>", "ins>", "br/>"];
                        for (var j = 0; j < search.length; j++) {
                            var pos = ary[i].lastIndexOf(search[j], search[j].length + 1);
                            if (pos == 0 || (pos == 1 && ary[i].charAt(0) == '/')) {
                                ary[i] = (pos == 1 ? "/" : "") + replace[j] + ary[i].substring(search[j].length + pos);
                            }
                        }
                        var spellcheckerRE = /^\/?span[^\/>]*\/?>/m;
                        var cleanupRE = /^(\/?)(br|b|del|ins|i|li|ol|a|p|ul)[^a-zA-Z\/>]*[^\/>]*(\/?)>/m;
                        if (ary[i].indexOf("href") == -1) {
                            if (spellcheckerRE.test(ary[i])) {
                                ary[i] = ary[i].replace(spellcheckerRE, "");
                            } else if (cleanupRE.test(ary[i])) {
                                ary[i] = ary[i].replace(cleanupRE, "<$1$2$3>");
                                ary[i] = ary[i].replace(/^<p>/, "");
                                ary[i] = ary[i].replace(/^<\/?p\/?>/, "<br/>");
                            } else {
                                ary[i] = end + 1 < ary[i].length ? ary[i].substring(end + 1) : "";
                            }
                        }
                        else {
                            ary[i] = '<' + ary[i];
                        }
                        ary[i] = ary[i].replace(/&nbsp;/gm, "");
                        ary[i] = ary[i].replace(/\n\n/gm, "\n");
                    }
                    html = ary.join("");
                    // Trim leading whitespace.
                    var trimRE = /^(\s+|&nbsp;|<br\/?>|<p>(&nbsp;)*<\/p>)+/m;
                    if (trimRE.test(html)) {
                        html = html.replace(trimRE, "");
                    }
                    // Test if there is any actual non-whitespace text content.
                    var body = document.getElementsByTagName("body")[0];
                    var div = document.createElement("div");
                    div.style.display = "none";
                    body.appendChild(div);
                    div.innerHTML = html;
                    var text = div.innerText || div.textContent;
                    body.removeChild(div);
                    var trimRE = /\S/m;
                    if (!trimRE.test(text)) html = "";
                    return html;
                };
            })(jQuery);
            editor = $('#SuccessStory_Description').cleditor({ controls: "bold italic underline | bullets numbering | link unlink" });
            editor2 = $('#SuccessStory_DescriptionIngles').cleditor({ controls: "bold italic underline | bullets numbering | link unlink" });
            ProblemsSolvedEditor = $('#SuccessStory_ProblemsSolved').cleditor({ controls: "bold italic underline | bullets numbering | link unlink" });
            ProblemsSolvedEditor2 = $('#SuccessStory_ProblemsSolvedIngles').cleditor({ controls: "bold italic underline | bullets numbering | link unlink" });
            SocialImpactEditor = $('#SuccessStory_SocialImpact').cleditor({ controls: "bold italic underline | bullets numbering | link unlink" });
            SocialImpactEditor2 = $('#SuccessStory_SocialImpactIngles').cleditor({ controls: "bold italic underline | bullets numbering | link unlink" });

            createEditor(editor);
            createEditor(editor2);
            createEditor(ProblemsSolvedEditor);
            createEditor(ProblemsSolvedEditor2);
            createEditor(SocialImpactEditor);
            createEditor(SocialImpactEditor2);

            function createEditor(objeto) {
                $(".cleditorMain iframe").each(function (index, obj) {
                    $(obj).contents().find('body').bind('paste', function () {
                        setTimeout(function () {
                            objeto[index].updateTextArea(objeto[index]);
                            var plainText = objeto[index].$area.val();
                            $(objeto[index].doc.body).html("");
                            $(objeto)[0].doc.execCommand("inserthtml", 0, plainText);
                        }, 100);
                    });
                });
            }
        });
     </script>
}
<div align="right">
    <ul id="MenuP">
        <li class="Menubig">@Resources.Global.Messages.DETAIL</li>
        <li>@Resources.Global.Messages.LIST</li>
    </ul>
    <div class="cont" align="left">
        @using (Html.BeginForm("Create", "SuccessStory", new { Area = "Admin" }, FormMethod.Post, new { id = "Form1", enctype = "multipart/form-data" }))
        {
        @Html.ValidationSummary()
        @Html.Hidden("GetOut", "0")
        @Html.Hidden("TempFiles")
        <hr />
        <div id="deepfolloweradmin">
            @Model.DeepFollower
        </div>
        @Html.Partial("_ContentPartial", Model);
        <div class="separator">
        </div>
        <div align="center" id="dvadicional" style="clear: both;">
            <h3>
                <img width="20" height="20" src="~/resources/images/nextwhite.png" /><span>@Resources.Global.Messages.ADDITIONAL_INFORMATION</span>
            </h3>
            @Html.HiddenFor(t => t.PostulateId)
            @Html.HiddenFor(t => t.SuccessStory.ContentId)
            @Html.HiddenFor(t => t.IContent.UserId)
            @Html.HiddenFor(t => t.IContent.LanguageId)
            @Html.HiddenFor(t => t.SuccessStory.CityID)
            <ul class="template" id="fields">
                <li>
                  @Resources.Global.Messages.CONTENT *<br />
                  @Html.EditorFor(t => t.SuccessStory.Description)
                </li>
                <li>
                    @Resources.Global.Messages.CONTENT2 *<br />
                    @Html.EditorFor(t => t.SuccessStory.DescriptionIngles)
                </li>
                <li>
                    @Html.Raw(Resources.Global.Messages.URBANSOLUTION)<br />
                    @Html.EditorFor(t => t.SuccessStory.ProblemsSolved)
                </li>
                <li>
                    @Html.Raw(Resources.Global.Messages.URBANSOLUTION2)<br />
                    @Html.EditorFor(t => t.SuccessStory.ProblemsSolvedIngles)
                </li>
                <li>
                    @Html.Raw(Resources.Global.Messages.PROBLEMSSOLVED)
                    @Html.EditorFor(t => t.SuccessStory.SocialImpact)
                </li>
                <li>
                    @Html.Raw(Resources.Global.Messages.PROBLEMSSOLVED2)
                    @Html.EditorFor(t => t.SuccessStory.SocialImpactIngles)
                </li>
                <li>
                  @Resources.Extend.Messages.INSTIMPLEM<br />
                  @Html.EditorFor(t => t.SuccessStory.InstitutionImplements)
                </li>
                <li>
                  @Resources.Extend.Messages.INSTSOURCE<br />
                  @Html.EditorFor(t => t.SuccessStory.InstitutionSource)
                </li>
                <li>
                  @Resources.Global.Messages.CATEGORY<br />
                  @Html.EditorFor(t => t.SuccessStory.Category)
                </li>
               <li>
                  @Html.Raw(Resources.Global.Messages.RELATEDURLS)
                  @Html.TextAreaFor(t => t.SuccessStory.Url, new { @cols = 80, @rows = 4 })
                </li>
               
            </ul>
        </div>
        }
        @if (Model.SuccessStory != null && Model.SuccessStory.ContentId != null)
        {
        <div align="center" id="dvadicional" style="clear: both;">
          <h3>
            <img width="20" height="20" src="~/resources/images/nextwhite.png" /><span>@Resources.Global.Messages.COMMENTS</span>
          </h3>
            @if (Model.ListComments != null && Model.ListComments.Count() > 0)
            {
            <ul class="template" id="comments">
              @foreach (Domain.Entities.FrontEnd.CommentsPaging comment in Model.ListComments)
              {
              <li class="comment">
                <input type="hidden" class="commentId" value="@comment.CommentId"/>
                <div class="commentValue">
                  <img src="@Business.Utils.fixLocalUserImagePath(comment.UserImage)" height="44"/>
                  <span>@comment.UserNames:</span>
                  <span>@comment.Text</span>
                  <img class="edit" src="@Url.Content("~/resources/images/25edit.gif")" alt="" title="Editar"/>
                  <img class="block" src="@Url.Content("~/resources/images/25cancel.gif")" alt="" title="Bloquear" style="display:@(comment.Active.Value ? "inline-block" : "none")"/>
                  <img class="unblock" src="@Url.Content("~/resources/images/accept.gif")" alt="" width="25" height="25" title="Desbloquear" style="display:@(comment.Active.Value ? "none" : "inline-block")"/>
                </div>
                <div class="commentForm" style="display:none;">
                  <input type="text" class="commentText" value="@comment.Text"/>
                  <img class="save" src="@Url.Content("~/resources/images/35save.gif")" alt="" title="Guardar"/>
                  <img class="cancel" src="@Url.Content("~/resources/images/35cancel.gif")" alt="" title="Cancelar"/>
                </div>
              </li>
              }
            </ul>
            }
        </div>
        }
        <div align="center" id="contentactions">
            <img onclick="$('#Form1').submit()" title="@Resources.Global.Messages.SAVE_EXIT" src="~/resources/images/45savewout.png" />
            @if (Model.IContent != null && Model.IContent.ContentId != null)
            {
                <img onclick="$('#GetOut').val('1');$('#Form1').submit()" title="@Resources.Global.Messages.SAVE" src="~/resources/images/45savew.png" />
            }
            <img onclick="window.location.href='@Url.Action("Index", "Content", new { Area = "Admin", mod = Model.Module.ModulId })'" title="@Resources.Global.Messages.CANCEL" src="~/resources/images/45cancelw.png" />
        </div>
    </div>
</div>