Webcore/Areas/Admin/Models/Content.cs
// <copyright file="Content.cs" company="Dasigno">
//     Copyright (c) 2013 All Rights Reserved
// </copyright>
// <author>Jimmy Rodriguez</author>
namespace Webcore.Areas.Admin.Models
{
    using System.Collections.Generic;
    using Business.Services;
    using Domain.Entities;
    
    /// <summary>
    /// management the content information
    /// </summary>
    public class Content : IAdmin
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Content"/> class
        /// </summary>
        public Content()
        {
        }

        /// <summary>
        /// Gets or sets a list of content
        /// </summary>
        public IEnumerable<Domain.Entities.Content> CollContent { get; set; }

        /// <summary>
        /// Gets or sets a list of sections
        /// </summary>
        public IEnumerable<Domain.Entities.Section> CollSection { get; set; }

        /// <summary>
        /// Gets or sets a total number of contents
        /// </summary>
        public int Total { get; set; }

        /// <summary>
        /// Gets or sets a name of controller
        /// </summary>
        public string Controller { get; set; }

        /// <summary>
        /// Gets or sets the information module
        /// </summary>
        public Modul Module { get; set; }

        /// <summary>
        /// Gets or sets the list of modules
        /// </summary>
        public IEnumerable<Modul> ColModul { get; set; }

        /// <summary>
        /// Gets or sets a user application
        /// </summary>
        public CustomPrincipal UserPrincipal { get; set; }

        /// <summary>
        /// Gets or sets the language application
        /// </summary>
        public Language CurrentLanguage { get; set; }
    }
}

Webcore/Areas/Admin/Controllers/ContentController.cs
// <copyright file="ContentController.cs" company="Dasigno">
//     Copyright (c) 2013 All Rights Reserved
// </copyright>
// <author>Jimmy Rodriguez</author>
namespace Webcore.Areas.Admin.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Text;
    using System.Web;
    using System.Web.Mvc;
    using Business.Services;
    using Domain.Concrete;
    using Domain.Entities;
    using Webcore.Areas.Admin.Models;

    /// <summary>
    /// Controller for content module
    /// </summary>
    public class ContentController : AdminController
    {
        /// <summary>
        /// gets the home of content module
        /// </summary>
        /// <param name="mod">identifier of module</param>
        /// <returns>returns the result to action</returns>
        [ModulAuthorize]
        public ActionResult Index(int mod)
        {
            ContentRepository content = new ContentRepository(SessionCustom);
            ModulRepository modul = new ModulRepository(SessionCustom);
            SectionRepository objsection = new SectionRepository(SessionCustom);

            PaginInfo paginInfo = new PaginInfo()
            {
                PageIndex = 1
            };

            content.Entity.ModulId = mod;
            modul.Entity.ModulId = content.Entity.ModulId = mod;
            content.Entity.LanguageId = modul.Entity.LanguageId = CurrentLanguage.LanguageId;
            modul.Load();

            ////objsection.Entity.Active = true;
            objsection.Entity.LanguageId = CurrentLanguage.LanguageId;

            if (HttpContext.Session["CollClones"] != null)
            {
                ViewBag.CollClone = (List<int>)HttpContext.Session["CollClones"];
            }

            return this.View(new Models.Content()
            {
                UserPrincipal = CustomUser,
                Module = modul.Entity,
                CollSection = objsection.GetAll().Where(t => t.ParentId == null),
                ColModul = CustomMemberShipProvider.GetModuls(CustomUser.UserId, SessionCustom, HttpContext),
                CollContent = content.GetAllPaging(null, paginInfo),
                Total = paginInfo.TotalCount,
                Controller = modul.Entity.Controller,
                CurrentLanguage = CurrentLanguage
            });
        }

        /// <summary>
        /// Obtains a string information to render item content list
        /// </summary>
        /// <param name="mod">identifier module</param>
        /// <param name="page">page index</param>
        /// <param name="sectionId">identifier section</param>
        /// <param name="name">criteria search</param>
        /// <param name="filter">order filter</param>
        /// <param name="active">content active</param>
        /// <returns>returns the result to action</returns>
        [HttpPost]
        public JsonResult GetContent(int mod, int page, int? sectionId, string name, short? filter, bool? active)
        {
            StringBuilder strbl = new StringBuilder();

            ContentRepository content = new ContentRepository(SessionCustom);
            PaginInfo paginInfo = new PaginInfo()
            {
                PageIndex = page
            };

            content.Entity.Name = name;
            content.Entity.Active = active;
            content.Entity.SectionId = sectionId;
            content.Entity.ModulId = mod;
            content.Entity.LanguageId = CurrentLanguage.LanguageId;

            IEnumerable<Domain.Entities.Content> contents = content.GetAllPaging(filter, paginInfo);
            foreach (Domain.Entities.Content item in contents)
            {
                strbl.AppendLine("<li id=\"li" + item.ContentId + "\" ondblclick=\"ctnback.editcontent(" + item.ContentId + ")\" onclick=\"if(ctnback.clicOk) { ctnback.contentselect(this, " + item.ContentId + "); } else { ctnback.clicOk = true; }\">");
                ////strbl.AppendLine("<input style=\"float:right;\" onclick=\"ctnback.clicOk=false;\" type=\"checkbox\" value=\"" + item.ContentId + "\" />");
                strbl.AppendLine("<img order=\"" + item.Orderliness + "\" id=\"" + item.ContentId + "\" class=\"handle\" src=\"" + Business.Utils.GetImageContent(item.Image, item.ContentId.Value, 44, 44) + "\" width=\"44\" height=\"44\" />");
                strbl.AppendLine("<div class=\"info-content\"><span title=\"Arrastre hacia una sección para cambiarla.\" class=\"sptitle cursor\">" + Business.Utils.TruncateWord(item.Name, 85) + "</span><br />");
                strbl.AppendLine("<span class=\"spdate\">" + item.Joindate.Value.ToString("F") + "</span></div><div class=\"clear\"></div>");
                strbl.AppendLine("</li>");
            }

            return this.Json(new { html = strbl.ToString(), count = contents.Count(), total = paginInfo.TotalCount }, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// obtains the content detail
        /// </summary>
        /// <param name="id">identifier content</param>
        /// <returns>returns the result to action</returns>
        [Authorize]
        public ActionResult ViewDetail(int id)
        {
            ContentRepository objcont = new ContentRepository(SessionCustom);
            UserRepository objuser = new UserRepository(SessionCustom);
            SectionRepository objSection = new SectionRepository(SessionCustom);
            ContentrelationRepository objrel = new ContentrelationRepository(SessionCustom);
            objrel.Entity.ContentId = id;

            objcont.Entity.ContentId = id;
            objcont.Load();

            objuser.Entity.UserId = objcont.Entity.UserId;
            objuser.Load();

            return this.View(new InfoContent()
            {
                Content = objcont.Entity,
                Autor = objuser.Entity.Names,
                DeepFollower = Business.Utils.GetDeepFollower(objSection.GetAll(), objcont.Entity.SectionId.Value),
                CountContent = objrel.GetAllReadOnly().Count
            });
        }

        /// <summary>
        /// delete a content item
        /// </summary>
        /// <param name="listContentId">list of id content</param>
        /// <returns>returns the result to action</returns>
        [HttpPost]
        [Authorize]
        public JsonResult DeleteContent(string listContentId)
        {
            string[] listofIds = listContentId.Split(',');

            ContentManagement objcontent = new ContentManagement(SessionCustom, HttpContext);
            objcontent.DeleteContent(listofIds);
            return this.Json(new { result = true }, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// displays the content relation page
        /// </summary>
        /// <param name="contentId">identifier content</param>
        /// <param name="page">index page</param>
        /// <param name="name">criteria search</param>
        /// <returns>returns the result to action</returns>
        [Authorize]
        public ActionResult ContentRelation(int contentId, int? page, string name)
        {
            ContentRepository objcontent = new ContentRepository(SessionCustom);
            PaginInfo paginInfo = new PaginInfo()
            {
                Size = 7,
                PageIndex = page != null ? page.Value : 1
            };

            objcontent.Entity.ContentId = contentId;
            objcontent.Entity.Name = name;

            return this.View(new ContentsRelations()
            {
                CollContentNoRel = objcontent.GetContentNoRelation(paginInfo, CurrentLanguage.LanguageId.Value),
                CollContentRel = objcontent.GetContentRelation(CurrentLanguage.LanguageId.Value),
                Pagininfo = paginInfo
            });
        }

        /// <summary>
        /// attach content to other content
        /// </summary>
        /// <param name="id">identifier of content to attach</param>
        /// <param name="contentId">identifier of primary content</param>
        /// <param name="name">criteria search</param>
        /// <returns>returns the result to action</returns>
        [Authorize]
        public ActionResult Attach(int id, int contentId, string name)
        {
            ContentManagement objcontent = new ContentManagement(SessionCustom, HttpContext);
            objcontent.AttachDettachContent(contentId, id, true);

            return this.RedirectToAction(
                "ContentRelation",
                new
                {
                    ContentId = contentId,
                    name = name
                });
        }

        /// <summary>
        /// detach content from other content
        /// </summary>
        /// <param name="id">identifier of content detach</param>
        /// <param name="contentId">identifier of primary content</param>
        /// <param name="name">criteria search</param>
        /// <returns>returns the result to action</returns>
        [Authorize]
        public ActionResult Dettach(int id, int contentId, string name)
        {
            ContentManagement objcontent = new ContentManagement(SessionCustom, HttpContext);
            objcontent.AttachDettachContent(contentId, id, false);

            return this.RedirectToAction(
                "ContentRelation",
                new
                {
                    ContentId = contentId,
                    name = name
                });
        }

        /// <summary>
        /// detach content from other content
        /// </summary>
        /// <param name="id">identifier of content detach</param>
        /// <param name="contentId">identifier of primary content</param>
        /// <returns>returns the result to action</returns>
        [Authorize]
        [HttpPost]
        public JsonResult DettachAjax(int id, int contentId)
        {
            ContentManagement objcontent = new ContentManagement(SessionCustom, HttpContext);
            return this.Json(

Webcore/Areas/Admin/Views/Content/ContentRelation.cshtml
@model Webcore.Areas.Admin.Models.ContentsRelations

@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>@Resources.Global.Messages.RELATED_CONTENT</title>
    @Styles.Render("~/resources/css/")
    @Scripts.Render("~/bundles/jquery")
    <script src="@Url.Content("~/resources/scripts/jquery-ui-1.10.3.min.js")" type="text/javascript"></script>
    @Scripts.Render("~/bundles/jqueryval")
    <style>
        body { background-color: White; }
        .tit { font-size: 18px; font-family: Segoe UI Light; background-color: #25A0DB; color: White; padding-bottom: 15px; }
        .dleft { float: left; width: 315px; padding: 5px; }
        .connectedSortable { padding: 0px; }
        .connectedSortable li { border-bottom: 1px solid gray; list-style: none; background-color: White; font-size: 16px; }
        .connectedSortable img { padding: 5px; }
        #sortable1 span { cursor: move; }
        #sortable2 { min-height:450px; }
        #sortable2 img { cursor:pointer; }
    </style>
    <script>
        $(function () {
            $("#sortable1, #sortable2").sortable({
                connectWith: "#sortable2",
                cursor: 'move',
                stop: function (event, ui) {
                    window.location.href = '@Url.Action("Attach")?id=' + ui.item.attr('id') + '&contentId=@Request.QueryString["ContentId"]';
                }

            }).disableSelection();
        });

        dettach = function(id) {
            window.location.href = '@Url.Action("Dettach")?id=' + id + '&contentId=@Request.QueryString["ContentId"]';
        };

        findall = function () {
            if ($('#find').val() != '' && $('#find').val() != 'Busca por nombre del contenido') {
                window.location.href = '@Url.Action("ContentRelation")?contentId=@Request.QueryString["ContentId"]&name=' + $('#find').val();
            }
            else {
                window.location.href = '@Url.Action("ContentRelation")?contentId=@Request.QueryString["ContentId"]';
            }
        };
    </script>
</head>
<body>
    <div style="width: 650px; height: 650px; border: 1px solid gray;">
        <img onclick="window.parent.closediv()" style="cursor: pointer;" align="right" src="@Url.Content("~/resources/images/closer.png")" />
        <div class="tit">
            @Resources.Global.Messages.RELATED_CONTENT</div>
        <div class="dleft">
            <span class="spntitle">@Resources.Global.Messages.CONTENT_AVAILABLE</span>
            <div>
                <img onclick="findall()" style="float: left; margin-right: 5px; cursor:pointer;" src="@Url.Content("~/resources/images/25search.gif")" />
                <input onkeypress="findsubm(event, function() { findall();  })" onblur="blurfind(this, '@Resources.Extend.Messages.FIND_BY_NAME')" onfocus="focusfind(this, '@Resources.Extend.Messages.FIND_BY_NAME')" value="@(Request.QueryString["name"] != null ? Request.QueryString["name"] : @Resources.Extend.Messages.FIND_BY_NAME)" id="find" class="textfind inactive" type="text" /></div>
            <ul id="sortable1" class="connectedSortable">
                @foreach (Domain.Entities.ContentRel item in Model.CollContentNoRel)
                {
                    <li id="@item.ContentId">
                    <span class="sptitle">@item.Name</span><br />
                    <span class="spdate">@item.ModulName</span>
                    </li>                    
                }
            </ul>
            <div align="right">
                 @(new Business.Paginator(HttpContext.Current, Model.Pagininfo).GetPaginator())
            </div>
        </div>
        <div class="dleft">
            <span class="spntitle">@Resources.Global.Messages.RELATED_CONTENT</span>
            <ul id="sortable2" class="connectedSortable">
                @foreach (Domain.Entities.ContentRel item in Model.CollContentRel)
                {
                <li id="@item.ContentId">
                    <img onclick="dettach(@item.ContentId)" align="right" title="Desasociar contenido" src="@Url.Content("~/resources/images/25del.gif")" />
                    <span class="sptitle">@item.Name</span><br />
                    <span class="spdate">@item.ModulName</span></li>    
                }
            </ul>
        </div>
    </div>
</body>
</html>

Webcore/Areas/Admin/Views/Content/Index.cshtml
@model Webcore.Areas.Admin.Models.Content
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    List<int> coll = ViewBag.CollClone;
}
<script type="text/javascript">
    var ctnback = new contentclass();
    ctnback.NotFound = '@Resources.Extend.Messages.NO_RECORDS_FOUND';
    ctnback.TextFind = '@Resources.Extend.Messages.FIND_BY_NAME';
    ctnback.UrlNewContent = '@Url.Action("Index", Model.Module.Controller, new { Area = "Admin", mod = Model.Module.ModulId })';
    ctnback.UrlDetailContent = '@Url.Action("Detail", Model.Module.Controller, new { Area = "Admin", mod = Model.Module.ModulId })';
    initialize = function () { ctnback.droppable(); }

    $(function () {
        ctnback.resizable();
        ctnback.sortable();
        ctnback.draggable();
        ctnback.droppable();
    });
    $(document).ready(function () {
        switch(@(Model.Module.ModulId)){
            case 51:
                $('#31 span').click();
                break;
            case 52:
                $('#32 span').click();
                break;
            case 54:
                $('#34 span').click();
                break;
            case 1065:
                $('#46 span').click();
                break;
            case 55:
                $('#0 span').click();
                $('#newcontent').hide();
                break;
            case 58:
                $('#35 span').click();
                break;
            case 61:
                $('#newcontent').hide();
                $('#36 span').click();
                break;
            case 60:
                $('#newcontent').hide();
                $('#37 span').click();
                break;
            case 62:
                $('#42 span').click();
                break;
        }
        $('#conttreecontent').hide();
        if($('#SectionId').val() != '46'){
            $("#postulateList").hide();
        }else{
            var postulateListUrl = $("#postulateList").attr("href") + '&sectionId=' + $('#SectionId').val();
            $("#postulateList").attr("href", postulateListUrl);
        }
    });
</script>
<ul id="MenuP">
    <li class="Menubig">@Resources.Global.Messages.LIST</li>
    <li>@Resources.Global.Messages.DETAIL</li>
</ul>
<div class="cont" align="left">
    <div>
        <a onclick="ctnback.cleanall()" class="hrefmen" href="javascript:void(0);">
            <img title="@Resources.Global.Messages.CLEAN" id="imgmore" border="0" width="23" height="23" src="~/resources/images/25clean.gif" />
        </a>
        <a class="hrefmen" onclick="ctnback.newcontent('@Resources.Extend.Messages.VALID_SECTION_CONTENT')" href="javascript:void(0);" id="newcontent">
            <img border="0" width="23" height="23" src="~/resources/images/25add.gif" />
            <span>@Resources.Global.Messages.NEW</span>
        </a>&nbsp;&nbsp;
        <a onclick="ctnback.deleteall()" class="hrefmen" href="javascript:void(0);" style="display: none;">
            <img border="0" width="23" height="23" src="~/resources/images/25del.gif" />
            <span>@Resources.Global.Messages.DELETE</span>
        </a>&nbsp;&nbsp;
        <a onclick="$('#loading').show();ctnback.findall(1, @Model.Module.ModulId);" class="hrefmen" href="javascript:void(0);">
            <img border="0" width="23" height="23" src="~/resources/images/25search.gif" />
            <span>@Resources.Global.Messages.FIND</span>
        </a>&nbsp;&nbsp;
        <input onkeypress="findsubm(event, function() { ctnback.findall(1, @Model.Module.ModulId); })" onblur="blurfind(this, '@Resources.Extend.Messages.FIND_BY_NAME')" onfocus="focusfind(this, '@Resources.Extend.Messages.FIND_BY_NAME')"
               id="txname" class="textfind inactive" value="@Resources.Extend.Messages.FIND_BY_NAME"
               type="text" />
        <input type="hidden" id="SectionId" />
        <input type="hidden" id="idCount" value="@Model.CollContent.Count()" />
        <input type="hidden" id="idPage" value="1" />
        <input type="hidden" id="ModulId" value="@Model.Module.ModulId" />
    </div>
    <div id="more">
        <div>@Resources.Extend.Messages.APPLY_FILTERS</div>
        <select onchange="$('#loading').show();ctnback.findall(1, @Model.Module.ModulId);" id="ddlstatus" class="dropsfil">
            <option>-@Resources.Global.Messages.STATUS-</option>
            <option value="true">@Resources.Global.Messages.ACTIVE</option>
            <option value="false">@Resources.Global.Messages.INACTIVE</option>
        </select>
        <select onchange="$('#loading').show();ctnback.findall(1, @Model.Module.ModulId);" id="ddlfilter" class="dropsfil">
            <option>-@Resources.Global.Messages.SORT-</option>
            <option value="0">@Resources.Extend.Messages.MANUAL_ORDER</option>
            <option value="1">@Resources.Global.Messages.CREATION_DATE</option>
            <option value="2">@Resources.Global.Messages.NAME</option>
        </select>
    </div>

    @Html.ActionLink(Resources.Global.Messages.POSTULATIONSLIST, "List", "SuccessStoryPostulate", new { mod = Model.Module.ModulId }, new { id = "postulateList" })
    <hr />
    <div id="contenttreecont">
        <div id="divslice">
            <div id="conttreecontent">
                <span class="spntitle">@Resources.Global.Messages.SECTIONS</span>
                <ul>
                    <li>
                        <div id="0">
                            <img height="15" width="15" src="~/resources/images/15add.gif" />
                            <span onclick="ctnback.binddetail(0)">@Resources.Global.Messages.ALL</span>
                        </div>
                    </li>
                    @foreach (Domain.Entities.Section item in Model.CollSection)
                    {
                        <li>
                            <div id="@item.SectionId">
                                <nobr>
                                    <img onclick="expand(this, @item.SectionId);" height="15" width="15" src="~/resources/images/15add.gif" />
                                    <span onclick="ctnback.binddetail2(@item.SectionId)">@item.Name</span>
                                </nobr>
                            </div>
                        </li>
                    }
                </ul>
            </div>
            <div id="contctncontent">
                <span class="spntitle">@Resources.Global.Messages.CONTENTS</span>
                <ul id="listado">
                    @foreach (Domain.Entities.Content item in Model.CollContent)
                    {
                        <li id="li@(item.ContentId)" ondblclick="ctnback.editcontent(@item.ContentId)" onclick="if(ctnback.clicOk) { ctnback.contentselect(this, @item.ContentId); } else { ctnback.clicOk = true; }">
                            @*<input style="float:right;" onclick="ctnback.clicOk = false;" type="checkbox" value="@item.ContentId" />*@
                            <img order="@item.Orderliness" id="@item.ContentId" class="handle" style="float:left;" src="@Business.Utils.GetImageContent(item.Image, item.ContentId.Value, 44, 44)" width="44" height="44" />
                            <div class="info-content">
                                <span title="Arrastre hacia una sección para cambiarla." class="sptitle cursor">@Business.Utils.TruncateWord(item.Name, 85)</span><br />
                                <span class="spdate">@item.Joindate.Value.ToString("F")</span>
                            </div>
                            <div class="clear"></div>
                        </li>
                    }
                </ul>
                <div style="@(Model.Total <= 8 ? "display:none;" : "display:block;")" id="dvpaginator" align="left">
                    <img style="cursor: pointer;" onclick="ctnback.contentpagin(@Model.Module.ModulId)" width="25" height="25"
                         src="~/resources/images/25down.gif" />
                    <span>
                        <span id="spnnumregis">@Model.CollContent.Count()</span> @Resources.Global.Messages.FROM <span id="spnresult">@Model.Total</span>
                        @Model.Module.Name
                    </span>
                </div>

            </div>
        </div>
    </div>
</div>
<div style="display: none;" align="center" id="contentactions">
    <input id="contentid" type="hidden" />
    <img onclick="ctnback.editcontent($('#contentid').val())" title="@Resources.Global.Messages.EDIT" src="~/resources/images/45editw.png" />
    <img onclick="if(confirm('@Resources.Extend.Messages.DELETE_ITEM')) { ctnback.deletecontent($('#contentid').val()); }" title="@Resources.Global.Messages.DELETE" src="~/resources/images/45deletew.png" style="display:none;" />
    <img onclick="opendiv(450,350,'@Url.Action("ViewDetail", "Content", new { Area = "Admin" })?id=' + $('#contentid').val());" title="@Resources.Global.Messages.INFORMATION" src="~/resources/images/45iw.png" />
    <img onclick="opendiv(650,650,'@Url.Action("ContentRelation", "Content", new { Area = "Admin" })?contentId=' + $('#contentid').val())" title="@Resources.Global.Messages.RELATED_CONTENT" src="~/resources/images/45refreshi.png" />
    <img onclick="$('.liact').removeClass('liact');$('#contentactions').slideUp();$('#contentid').val(null);" title="@Resources.Global.Messages.CANCEL" src="~/resources/images/45cancelw.png" />
    <img onclick="ctnback.addClone($('#contentid').val(), '@Resources.Global.Messages.CLONE_CONTENT', '@Resources.Extend.Messages.VALID_SECTION_CONTENT')" title="@Resources.Global.Messages.CLONE_CONTENT" src="~/Resources/Images/clone.png" style="display:none;" />
</div>
@if (coll != null)
{
    @:<div id="dvClone"><img onclick="ctnback.CloneContent('@Resources.Extend.Messages.VALID_SECTION_CONTENT')" title="@Resources.Global.Messages.CLONE_CONTENT" src="@Url.Content("~/Resources/Images/clone.png")"><span>@coll.Count</span></div>
}

Webcore/Areas/Admin/Views/Content/ViewDetail.cshtml
@model Webcore.Areas.Admin.Models.InfoContent

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>@Model.Content.Name</title>
    @Styles.Render("~/resources/css/")
    <style>
        body { background-color:White; }
        .tit { font-size:18px; font-family:Segoe UI Light; background-color:#25A0DB; color:White; padding-bottom:15px; min-height:70px; }
        #det { margin:0px; padding:0px; clear:both; margin-left:10px; }
        #det li { list-style:none; }
        #det span { font-size:15px;  }
        #det label { font-size:12px; color:#25A0DB; margin-left:5px;  }
        .imgp { margin:5px; border:1px solid white; }
    </style>
</head>
<body>
    <div style="width:450px; height:255px;">
        <img onclick="window.parent.closediv()" class="img-close-div" src="~/resources/images/closer.png" />
        <img class="imgp" align="left" width="70" height="70" src="@Business.Utils.GetImageContent(Model.Content.Image, Model.Content.ContentId.Value, 70, 70)" />
        <div class="tit" style="line-height:18px; padding-top:10px;">@Model.Content.Name</div>
        <ul id="det">
            <li>
                <span>@Resources.Global.Messages.FRIENDLY_URL</span><br />
                <label>@Model.Content.Frienlyname</label>
            </li>
            <li>
                <span>@Resources.Global.Messages.SECTION</span><br />
                <label>@Model.DeepFollower</label>
            </li>
            <li>
                <span>@Resources.Global.Messages.CREATION_DATE</span><br />
                <label>@Model.Content.Joindate.Value.ToString("F") </label>
            </li>
            <li>
                <span>@Resources.Global.Messages.MODIFIED_DATE</span><br />
                <label>@Model.Content.Updatedate.Value.ToString("F")</label>
            </li>
            <li>
                <span>@Resources.Global.Messages.AUTHOR</span><br />
                <label>@Model.Autor</label>
            </li>
            <li>
                <span>@Resources.Global.Messages.RELATED_CONTENT</span><br />
                <label>@Model.CountContent</label>
            </li>
        </ul>
    </div>
</body>
</html>